#+TITLE: Doom Literate Config
#+STARTUP: overview
Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!

Just some lisp code to kill emacs
(save-buffers-kill-emacs)
* General
Emacs start in fullscreen mode

#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+END_SRC

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC emacs-lisp
;(setq display-line-numbers-type t)
(setq display-line-numbers-type 'nil)
#+END_SRC


Who am I?

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.
#+BEGIN_SRC emacs-lisp
(setq user-full-name ""
      user-mail-address "")
#+END_SRC

Global zoom that works accross all buffers. By default it only works per buffer.
#+BEGIN_SRC emacs-lisp
;; (defadvice text-scale-increase (around all-buffers (arg) activate)
;;   (dolist (buffer (buffer-list))
;;     (with-current-buffer buffer
;;       ad-do-it)))
#+END_SRC

** Themes
#+BEGIN_SRC emacs-lisp
;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important one:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:

;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-vibrant)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
#+END_SRC
* Org
The amazing organizer mode, this is just some general configs
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/org/")
;; For org linking
(setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)

(after! org (org-add-link-type "onenote" 'org-onenote-open) (
  defun org-onenote-open (link) "Open the OneNote item identified by the unique OneNote URL."
    (w32-shell-execute "open" "C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\ONENOTE.exe" (concat "/hyperlink " "onenote:" (shell-quote-argument link))
)))

(map! (:map evil-normal-state-map
       "C-c a" #'org-agenda))
#+END_SRC

* Projectile
This adds projects to projectile. By default I added everything in my work
directory as well as my org directory. Also removes.emacs.d cause all the
configuration is done in .doom.d...
#+BEGIN_SRC emacs-lisp
(projectile-add-known-project "C:/Users//AppData/Roaming/org")
(projectile-add-known-project "C:/Users//AppData/Roaming/.doom.d")
;; sometimes glitches out, run (projectile-discover-projects-in-search-path)
;; to reload projects
(setq projectile-project-search-path '("C:/Users//Documents/work"))

#+END_SRC

This prevents new workspaces from being opened up with every new emacsclient connection
(when you use REmacs), rather it just creates a workspace main, if it already exists
switches to it
#+BEGIN_SRC emacs-lisp
(after! persp-mode
  (setq persp-emacsclient-init-frame-behaviour-override "main"))
#+END_SRC

This mapping allows for easy access to eshell, it also has a function
for switching to the buffer/creating it if it's not in a currently visible
frame
#+BEGIN_SRC emacs-lisp
(map! (:leader
       (:prefix "o"
        :desc   "Treemacs"              :nv "t" #'treemacs
        :desc   "Project eshell"        :nv "e" #'switch-to-project-eshell-else-create)))

;; Simple function to create project eshell if it exists, else switch to it
(defun switch-to-project-eshell-else-create ()
  (interactive)
  (let ((eshellBuffer (concat "*eshell " (projectile-project-name) "*")))
     (if (get-buffer-window eshellBuffer 'visible)
        (if (string= (buffer-name) eshellBuffer)
            (print '"already in eshell buffer")
          (switch-to-buffer-other-frame eshellBuffer))
        (progn (split-window)
               (command-execute 'projectile-run-eshell)
               (evil-window-move-very-bottom)
               (evil-window-set-height 10)
               ))))
#+END_SRC
* lsp
Syntax highlighting, error checking, all the good stuff you want. This adds some
simple bindings for some common lsp commands
#+BEGIN_SRC emacs-lisp
(map! (:leader
       (:prefix ("l" . "lsp")
        :desc   "Run lsp"               :nv "l" #'lsp
        :desc   "Format Buffer"         :nv "f" #'lsp-format-buffer)))
#+END_SRC
* Evil
Vim keybindings! Just binding a few things to the evil mode map
#+BEGIN_SRC emacs-lisp
(map! ;; Maps C-w C-; to hydra window nav for easier window resizing
       (:map evil-window-map
       "C-;" #'+hydra/window-nav/body)
      ;; Map csg in evil normal state map to project search
      (:map evil-normal-state-map
       "C-S-f" #'+ivy/project-search))
#+END_SRC
* Eyebrowse
TODO, this isn't fully fleshed out yet... In essence it's a frame saver that can
create tabs w/different frame layouts. Unfortunately it doesn't work well with
projectile right now, there's some glue for it, but I haven't set it up yet, [[https://github.com/syl20bnr/spacemacs/pull/4068][here's]]
some glue code for spacemacs that I can probably get to work... Probably

#+BEGIN_QUOTE
(map! (:leader
      ;; Unbind browse things in magit-mode map to enable eyebrowse
      (:map magit-mode-map
       "C-c C-w" #'nil)))

(defcustom eyebrowse-keymap-prefix (kbd "C-a")
  "Prefix key for key-bindings."
  :type 'string
  :group 'eyebrowse)

;; This unbinds it from doom/backward-to-bol-or-indent, giving it to eyebrowse
(undefine-key! "C-a")
#+END_QUOTE

* Company
Auto completion framework that makes the auto complete options pop up at the bottom.
By default the suggestions are disabled (by hlissner), this re-enables them with the
Company defaults
#+BEGIN_SRC emacs-lisp
;; Enabling Company defaults
(setq company-idle-delay 0.1
      company-minimum-prefix-length 2)
#+END_SRC




* Default Text Scaling
This is to enable text scaling rather than just zoom. Enables zoom in everything,
including modeline and stuff, I hope
#+BEGIN_SRC emacs-lisp
;(default-text-scale-mode 't)
#+END_SRC
